---
namespace: kubernetes-testing
domain: jamesclonk.io
random_names: true

lets_encrypt:
  issuer: letsencrypt-staging
  server: https://acme-staging-v02.api.letsencrypt.org/directory

longhorn:
  enabled: false
pvc:
  enabled: false
