name: Run specs

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  k8s-testing:
    name: 'k8s-testing'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Setup configs
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${KUBECONFIG}" > kubeconfig

    - name: Setup Chrome
      uses: ./.github/actions/setup-chrome

    - name: Run k8s-testing specs
      run: |
        export KUBECONFIG=kubeconfig
        make test

    - name: Cleanup
      if: ${{ always() }}
      run: |
        rm -f kubeconfig || true
        rm -f config.yml || true
